name: Publish-NPM

on:
  push:
    branches: 
      - master
jobs:
  release:
    name: ğŸš€ Release to NPM
    runs-on: ubuntu-latest
    steps: 
      - name: â¬ Checkout
        uses: actions/checkout@v2

      - name: ğŸ§¬ Setup Node
        uses: actions/setup-node@v2.3.0
        with:
          registry-url: https://registry.npmjs.org

      - name: ğŸŒµ Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: âŒ› Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: âš™ï¸ Build
        run: npm run build

      - name: ğŸš€ Publish
        run: npm publish --access public
        env: 
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}} 